### ISSUE TITLE
Your test duration measurement is inaccurate

### ISSUE THREAD

**Issue by dead-claudia** [tinylibs/tinybench#143]
> Related: https://github.com/tinylibs/tinybench/issues/65

Performance measurement is unfortunately not as simple as `performance.now()` in browsers. Further, operating systems can and do sometimes have resolution limits of their own.

Here's some considerations that need to be addressed, in general:

- Browsers are required [by spec](https://w3c.github.io/hr-time/#dfn-coarsen-time) to coarsen resolution to a minimum of 5 microseconds (200k ticks/sec) in isolated contexts and 100 microseconds (10k) in non-isolated contexts, [for security and privacy reasons](https://github.com/w3c/hr-time/issues/79).
- Most browsers reduce resolution even further, but to varying degrees per https://github.com/w3c/hr-time/issues/56
    - Firefox: 20us (50k ticks/sec)
    - Chrome: 100us + 100us jitter (5-10k)
    - Safari: 1ms (1k)
    - Edge pre-Chromium: 20us + 20us jitter (25-50k)
    - Brave: 1ms (1k) per https://github.com/brave/brave-core/pull/15309
- On Windows, all browsers' `performance.now()` tick during sleep. In other platforms, they don't, in violation of the spec: https://github.com/w3c/hr-time/issues/115#issuecomment-1172985601
    - The ramifications mostly apply to async tests and tests using atomics.

The benchmarks currently naively use start and end `performance.now()`/`process.hrtime.bigint()` calls. The precision issues can give you bad data, but it's not insurmountable:

- Any test run that completes in less than half of the minimum timer precision is statistically indistinguishable from a test where the JIT optimized everything out. You could compare that to a null test, count the difference in timer ticks, and use that to build your time estimate, but even then, you'd need a massive number of runs to get much confidence from that. And for tests like ours where we need to measure frame times, in browsers like Brave and Safari where timer resolution is 1ms, this could require a very long time for some tests. (This isn't theoretical - one of our render tests in [this PR](https://github.com/MithrilJS/mithril.js/pull/2982) ran 147169 times at an average of 0.03 ms/run or ~33k ops/sec, and that many frames at 60 FPS would come out to about 41 minutes.)
- If the test completes in more than half a unit of precision but less than 1.5 units, you could use similar tricks to gain more confidence, but you'd still need a decent number of runs if you're only measuring spans. You could just expect roughly half the runs since you have a roughly 100% chance of at least one tick happening in the code block.
- Even the act of measurement entails overhead (in the order of nanoseconds), so a null test is needed for accurately measuring at a resolution of more than about 100k ops/sec.

It doesn't appear [your benchmark execution code](https://github.com/tinylibs/tinybench/blob/44a8aef83f4d7145bb17f7ced560d9c428fc9490/src/task.ts#L72) currently takes any of this into account, hence this issue.

**Comment by jerome-benoit** [comment]
That's why the API: 

-  allows to define a custom timestamping function to fit environment needs, such as
  - `() => $.agent.monotonicNow()`
  - `() => $262.agent.monotonicNow()`
  - ...
- allows to define the benchmark behavior such as minimum benchmark iterations and time
- integrates JIT deoptimization

There's no one-size-fits-all benchmarking design in the JS ecosystem. But instead APIs allowing to refine the benchmark accordingly and sane defaults. 

What is actually missing in tinybench API to adapt it to browsers?

**Comment by dead-claudia** [comment]
@jerome-benoit I didn't realize you also used confidence - that means the jitter isn't of much concern.

But for the rest, in short, `duration` is inaccurate if the code executes faster than timer resolution:

```js
let start = now()
fn()
let end = now()
let duration = end - start
```

The concrete fix is this:

1. Run multiple `fn()` iterations instead of just one, repeating until you sufficiently exceed the clock's granularity. (I chose 15x, but that was just a random guesstimate that turned out to he good enough for my needs.) The time per run becomes `duration / iterations`.
    - Unfortunately, to avoid measuring `beforeEach` and `afterEach`, it'd be a breaking change. If you want to ensure accuracy while just doing one (to not break people), you'll need to alert people of this benchmarking limitation so they're aware, and possibly display a warning if it measures a zero-duration sample.
2. Use the iteration count as a weight for your statistical analysis, including your confidence analysis (for when to stop looping).

Changing the `now()` function is not a valid workaround - it's inherent to the granularity of its result. Not even adding a `durationSince(timestamp)` is sufficient.

**Comment by dead-claudia** [comment]
On a related note, maybe they should've called it `performance.subtle.now()`, not `performance.now()`, to align with `crypto.subtle`. Both seem to have a class of bugs that neither result in errors nor data returned that can be easily validated through automated means. 😅

**Comment by jerome-benoit** [comment]
> The concrete fix is this:
> 
> 1. Run multiple `fn()` iterations instead of just one, repeating until you sufficiently exceed the clock's granularity. (I chose 15x, but that was just a random guesstimate that turned out to he good enough for my needs.) The time per run becomes `duration / iterations`.

Benchmark warmup at `Bench` and `Task` level is supported and it has sane defaults for most case, that can be tuned.
The case where timestamping resolution is below the JS runtime timestamping is not solved by any means by incorrect measurement methodology such as measuring the latency of repeated benchmark function code and using the average as the latency of one function run: 
  * using an average as a primary source for statistical analysis introduce non anecdotal bias, cf. below 
  * a correct benchmark methodology must not modify the original experiment, it's a golden rule

>    * Unfortunately, to avoid measuring `beforeEach` and `afterEach`, it'd be a breaking change. 

Only the latency of the benchmarking function execution with JIT deoptimization is measured in tinybench.  

> If you want to ensure accuracy while just doing one (to not break people), you'll need to alert people of this benchmarking limitation so they're aware, and possibly display a warning if it measures a zero-duration sample.

A correct benchmark methodology means not modifying the experiment to time. Such as measuring the time a runner at doing 500m is *not* measuring the time and distance of one step repetitively and use the average of that measurement as a base to time his 500m course. It's utterly wrong in so many ways ... 

I've seen benchmarking tool such as mitata using a similar totally flawed methology. Tinybench will never go that path as we care about using unbiased measurement methodology.         

> 2. Use the iteration count as a weight for your statistical analysis, including your confidence analysis (for when to stop looping).

Tinybench is meant to be a lean library using state of the art benchmarking methods and advanced statistical results. The analysis of them such as determining if the margin of error is acceptable, the median absolute deviation is acceptable, ... and globally the statistical significance of the result will not be part of tinybench. It's up to the user to analyze them and eventually automate the detection of anomalies in the measurement. 
The statistical indicators analysis can be documented and more state of the art statistical indicators can be added (z-score, IQR, ...) - we take PRs -. 

> Changing the `now()` function is not a valid workaround - this issue is inherent to the granularity of that function's result. Not even adding a `durationSince(timestamp)` is sufficient.

The analysis of the result is meant to tell if a measurement is correct or not: for example the presence of a lot of zero measurement will make the margin of error go high for latency => results cannot be trusted. 

And using a totally flawed benchmarking methodology as a workaround to a too high resolution in the JS runtime timestamping is not an acceptable solution. The root cause must be fixed: not offering an optional mode with high resolution timer in a JS runtime is considered as a bug nowadays. And browsers can be started with high resolution timer for benchmarking purpose. 

So I repeat: what is actually missing in tinybench to run accurate benchmark using state of the art methodology in browsers?

**Comment by dead-claudia** [comment]
@jerome-benoit Just letting you know I plan to respond with precise numbers, just I've got a bunch of math (mostly stats and calculus) to work out.

May turn this into a whitepaper later for others to reference.

**Comment by jerome-benoit** [comment]
> @jerome-benoit Just letting you know I plan to respond with precise numbers, just I've got a bunch of math (mostly stats and calculus) to work out.

Precise numbers on how a flawed benchmarking methodology can give unbiased results? ;-)

1. Averaging an average is a well-known statistics 'avoid to do' things documented in all books. Even with the introduction of weights.
2. Altering the experiment to benchmark is the ultimate rule to **not** violate in the measurement theory.   

If you plan write down that violating theses two points will make a benchmark more accurate, the proof of the contrary is already settled since years.
The inaccuracy of timestamping in the measurement theory is a known issue and already handled by the statistical analysis of the sample of measurements.

**Comment by dead-claudia** [comment]
> > @jerome-benoit Just letting you know I plan to respond with precise numbers, just I've got a bunch of math (mostly stats and calculus) to work out.
> 
> Precise numbers on how a flawed benchmarking methodology can give unbiased results? ;-)

The hard numbers I'm working on are around why your benchmarking methodology is flawed. Mine is not any more perfect, but I'd have to do (a lot) more research to figure out how to correctly account for measurement error in general.

> 1. Averaging an average is a well-known statistics 'avoid to do' thing documented in all books. Even with the introduction of weights.

These aren't simple averages. They're population-weighted averages. https://en.wikipedia.org/wiki/Weighted_arithmetic_mean lists precisely the method I'm using as a valid use, just in a different context (average test grade).

And to be clear, when it comes to performance, there's three main statistics that matter most: the arithmetic mean, the upper end of the confidence interval, and (for real-time cases) the max value.

In the context I'm currently working with, I'm dealing with a soft real-time process where a certain function call must complete in under 5 microseconds on average and preferably under 2 microseconds. Yes, microseconds, not milliseconds. And yes, this obviously sits well below even the minimum `DOMHighResTimestamp` resolution allowed by spec.

> 2. Altering the experiment to benchmark is the ultimate rule to **not** violate in the measurement theory.   

Obviously, that *is* a concern. I in my current (not-yet-public) benchmarking code prepend a null test for this exact reason and make sure to print both raw stats including it and stats adjusted using numbers from a null test.

My adjusted stats displayed for those is admittedly *probably* biased and obviously not perfect, but fixing that would require a bunch of math that I currently don't plan to do in the near term. (I have more pressing priorities.)

> If you plan to write down that violating theses two points will make a benchmark more accurate, the proof of the contrary is already settled since years: Kolmorogov-Naguno publications on the generalization of the averaging concept - the f-mean has the correct properties if and only if f is injective -> a mean (weighted or not) is not injective -> using a mean as f-mean does not behave correctly.

The ultimate mean I'm returning isn't of the samples themselves, but of the (potentially unmeasurable) durations of each iteration plus the small but statistically significant measurement overhead.

Thing is, you don't need to know *all* values to have a mean. Simply knowing how many runs and how long all runs collectively took is sufficient. As wait times add just through the passage of time, you only need to measure the whole span to know how long all runs collectively took.

And non-weighted means (what these intermediate means are) with known population sizes can be correctly merged using population-weighted means. (You obviously can't do this with unknown populations. But the population size here *is* known.)

There are caveats, like the lack of a true min/max and a lack of a true median. But that goes without saying.

> The inaccuracy of timestamping in the measurement theory is a known issue and already handled by the statistical analysis of the sample of measurements. 

This is the part I'm working on, so I won't address it here right now.

**Comment by jerome-benoit** [comment]
> Thing is, you don't need to know _all_ values to have a mean. Simply knowing how many runs and how long all runs collectively took is sufficient. As wait times add just through the passage of time, you only need to measure the whole span to know how long all runs collectively took.

You still does not seem to really understand why it's plain wrong as a measurement method, why any weighted averages as a primary source of a measurements sample is just biased by definition and can't be used as a trusted source. 

Basically you're building a sample from imputed data using the mean. It has be proven since years to be non anecdotally biased: rubin's law introduction, distribution of samples comparaison methods, ...   

> And non-weighted means (what these intermediate means are) with known population sizes can be correctly merged using population-weighted means. (You obviously can't do this with unknown populations. But the population size here _is_ known.)

No, you can't. Or you have to prove that Kolmogorov-Nagumo where wrong on the generalization of the concept of averaging.

Since the beginning you are making incorrect statements on: 
- the way latency is measured in tinybench
- the statistics computed in tinybench
- the high-resolution timer supported granularity in JS runtimes  

And you continue with plain wrong statements about well-known mathematics proven results in the statistics field. 
No interesting outcomes are then expected.

I see not point in continuing such a discussion.

**Comment by dead-claudia** [comment]
Okay, closing. I'll agree to disagree, in particular on these two key points.

- [Kolmogorov-Nagumo f-means](https://en.wikipedia.org/wiki/Quasi-arithmetic_mean) somehow impacting the averaging of time delta samples (this was my key point in my previous comment)
- Weighted averages not applying to aggregate time delta samples

If I write up a whitepaper about this and get it peer reviewed, I may consider sharing it here. But aside from that, I'm ending the discussion. I doubt that even providing hard stats on how naively using this code provides skewed statistics or providing mathematical proofs that either of the two above bullets are false will change your opinions on the matter, so continuing it will be fruitless.

```js
let start = performance.now()
// do stuff
let end = performance.now()
let duration = end - start
```

> My calculations came out to about a 70% chance of undercounting a 20us interval and 30% chance of counting it as zero given Chrome's 100us granularity + 100us random jitter, by the way. I just hadn't yet either 1. calculated the expected mean value (specifically `Exp({Mean(S) for all S in possible sample sets})`) or 2. confirmed precisely how Chrome generates the value (which from a cursory code search appears to diverge from what I used to math out, but only slightly). But the two stats I have calculated suggest a very possible skew towards zero.
>
> I still plan to complete these calculations anyway, as you weren't the only considered audience for them.

**Comment by jerome-benoit** [comment]
> I doubt that even providing hard stats on how naively using this code provides skewed statistics or providing mathematical proofs that either of the two above bullets are false will change your opinions on the matter, so continuing it will be fruitless.

And the reason is simple: no mathematical proof of their fallacy exists, no counter examples exists. And if you had one to share, it will probably end up being a candidate for the field medal ... 
But one can give you tons of counter examples that averaging an average is biased, weighted or not. That doing measurement over a sleep interval on an async code execution design is not reliable per design, and a totally incorrect methodology to measure the timestamping accuracy on a JS runtime or even in general, ... (and the pile of technical and mathematical nonsense)

**Comment by neuronetio** [comment]
I encountered a similar problem with zero function time measurement which causes the test to take a long time (it skips zero functions and waits until it accumulates)

Until I got here and wanted to open an issue on this matter I lost a lot of time to find out more or less what it is about and why the tests "don't work".

I understand that you shouldn't measure the average because it gives bad results but in the end I will have to make a loop in my code to measure the average of operations below the threshold - because I have no other way to measure it?

Ok, theoretically I can make a loop myself - it's not a problem, but a large part of programmers don't know about it - they want to quickly test something and it seems to them that they have measured it :O they have some average and they do optimizations in their applications :O
Due to an incorrect assumption they lost a lot of time/money to implement "fixes" and then it turns out that they haven't measured anything at all :O (this can make a huge mess in the code)

It would be nice if you could do something for such cases which are probably not uncommon.

> It's up to the user to analyze them and eventually automate the detection of anomalies in the measurement.

I think it would be good to mention this problem (zero time) in the documentation for less advanced programmers
this problem seems to me to have significant consequences for us users of the library

**Comment by neuronetio** [comment]
Even when I make a loop I still don't know how big it should be and I have to guess when a given function will start returning a result above zero.

It would be useful to have some information in the API about empty values ​​to eliminate them.

**Comment by jerome-benoit** [comment]
As already explained at length several times: use an accurate time measurement stack (hardware/OS/JS runtime timestamping) meeting your precision needs. 
Looping over a test is NOT a solution to "approximate" one test execution totally wrongly. It's not even a bandaid, it's just incorrect at all levels one can think of. Despite the fact that some benchmarking tools claims picoseconds precision by using that "method", it's not theoretically possible. Even without a math proof, how anyone can think it's possible to measure accurately below the calibrated precision of your stack by using a programming trick? If it were possible, why bother doing atomic clocks? A Nobel prize would have rewarded such a discovery ...

There's an issue for adding a FAQ, you can comment on it to prioritize the content you think should be. Or even better, do PR to start it ;-)

**Comment by jerome-benoit** [comment]
The contradiction is lying in the terms: the precision in the minimum of the precision of each stack component.

**Comment by neuronetio** [comment]
But I don't need perfect precision - some precision is enough.

**Comment by jerome-benoit** [comment]
The contradiction is still lying in the terms: if some precision (like 100ms) is enough, why trying to do measurement on code needing precision below the stack precision?

**Comment by neuronetio** [comment]
Because it gives some "insight" if something takes around 100ms and around 500ms consistently?

**Comment by neuronetio** [comment]
When I create a loop I have this insight. Otherwise I have nothing.

**Comment by jerome-benoit** [comment]
No valid insights will be given by using a totally flawed measurement method. It's already part of previous comments: premature optimization , biased optimization, ...

**Comment by jerome-benoit** [comment]
A tool using a totally flawed measurement methodology to perform benchmarks is not beneficial to anyone. And can't help  to identify runtime bottleneck by definition.

**Comment by neuronetio** [comment]
not totally, but just like my predecessor I'll give up because it doesn't make sense anymore

**Comment by neuronetio** [comment]
FLEXIBILITY!!! :)

**Comment by jerome-benoit** [comment]
To make sense, proposition needs to come with in depth thoughts on the issue they want to tackle, no just accumulate bold claims like it was done previously ...

- loop optimization measurement issue?
- loop unroll measurement issue?
- loop measurement calibration methods?
- measurement uncertainty propagation in included statistical indicators?
- ...

**Comment by neuronetio** [comment]
If you have a critical function in which literally every operation is important because it is performed millions of times - looking for savings below the timer threshold is necessary because the savings are cumulative and may not be visible when we measure the application as a whole (or a few levels above the actual code).
I know that you don't test in isolation because the results can be distorted and only the final test will give real insight, but something like this is helpful anyway and brings the expected results in the form of cumulative savings (something like with money).
When we want to test simple data structures or other solutions to have a hint whether it is worth trying to implement it at all because it brings savings in isolation, we need to go below the threshold.

**Comment by neuronetio** [comment]
By applying changes piece by piece, we may not see the result - only when we introduce a lot of changes - to save time we need to have guidelines - so as not to act blindly. Additionally, it is much easier and faster to test a concept in isolation - without introducing far-reaching changes to our system.

**Comment by neuronetio** [comment]
The js engine implementation is hidden from us (because we don't have time to dig into the details and try to understand the browser code of each browser) so the fastest way is reverse engineering in the form of a quick benchmark test (imperfect but in this case the best way - most optimal hehe).

I understand that you don't want to loop and count everything because it would affect the test (experiment) result and additionally falsify the results (which are already falsified), but I think it would be a better solution (among others for the reasons given above).

**Comment by jerome-benoit** [comment]
Ask yourself: 

* Is digging up a problematic at various levels closed issue the best way to open a discussion on browser benchmarking precision? 
* Is introducing a proven to be flawed methodology to deal with that precision corner case issue an acceptable solution?
* Is there better alternatives that can be documented?  

Please use the right place if you want make to make propositions.

**Comment by dead-claudia** [comment]
@neuronetio As the original creator of this issue, you're wasting your time: https://github.com/tinylibs/tinybench/issues/143#issuecomment-2441894412

Please don't reboot this. And @jerome-benoit, feel free to lock this issue, so nobody else gets the idea to try to further it. We both agree that it isn't productive to continue the discussion in its current state.

If I ever produce that whitepaper (I have many way bigger priorities than that right now) and decide to share it here, I'll just create a new issue for it.
