### ISSUE TITLE
Incorrent timig with for loops

### ISSUE THREAD

**Issue by ShivamJoker** [tinylibs/tinybench#26]
This is my code which I am testing

```js
import { Bench } from "tinybench";

const bench = new Bench({ iterations: 100_000 });

bench
  .add("loop 1", () => {
    let sum = 1;
    for (let index = 0; indexindex < 10000; indexindex++) {
      sum = sum * index;
    }
  })
  .add("loop 2", () => {
    let sum = 1;
    for (let index = 0; indexindex < 10; indexindex++) {
      sum = sum * index;
    }
  });

await bench.run();

console.table(
  bench.tasks.map(({ name, result }) => ({
    "Task Name": name,
    "Time (ps)": result?.totalTime,
    "Variance (ps)": result?.variance * 1000,
  }))
);
```
The results are same in both

```
┌─────────┬───────────┬──────────────────────┬──────────────────────┐
│ (index) │ Task Name │      Time (ps)       │    Variance (ps)     │
├─────────┼───────────┼──────────────────────┼──────────────────────┤
│    0    │ 'loop 1'  │ 0.002133705863210011 │ 0.010551717975465412 │
│    1    │ 'loop 2'  │ 0.002180478539965521 │ 0.030143625437354347 │
└─────────┴───────────┴──────────────────────┴──────────────────────┘

```

I am using node v16.17.1

**Comment by Aslemammad** [comment]
Let me know which tinybench version you are using.

And see if this is related #27 #28

**Comment by Aslemammad** [comment]
ok! could you check if #28 solves your issue?

**Comment by kainstar** [comment]
It's your code's error, not tinybench's problem.

Please check your for loop end condition

```
for (let index = 0; indexindex < 10000; indexindex++)
```

You declare a veriable named `index`, but the end condition is using a undeclared varibale `indexindex`.

These two code has same time because when it execute, it would throw error immediately and never into loop.

When I test correct code on v2.3.0, it give such result:
<img width="504" alt="image" src="https://user-images.githubusercontent.com/15249633/196100663-8faeaa69-9004-448b-a494-d78fdfd02f19.png">

**Comment by ShivamJoker** [comment]
Aah sorry my mistake

**Comment by kainstar** [comment]
Maybe tinybench think throw error is also a way to complete a function?

**Comment by Aslemammad** [comment]
Please create a new issue in case! I don't think this is a problem anymore. Thanks.
